### ISSUE TITLE
Is WebexInjector.exe deprecated?

### ISSUE THREAD

**Issue by swingcake** [lacaulac/webex-anti-flash#2]
In the usage section of `WebexInjector.exe`, it states

> THIS IS NOT WORKING AT THE MOMENT

I'm really annoyed by WebEx and would like to end this madness that none of Cisco's engineers cares about, but `WebexAntiFlash.dll`

> prevents Webex and _any other application_ from making its taskbar icon flash

which is not what I really want.

At this stage, is this project a universal anti-flash or could I possibly just stop Cisco WebEx from doing so? Also, how does one revert the changes?

**Comment by lacaulac** [comment]
Sorry, the way I wrote it may have been unclear. 
If your goal is only to target WebEx, this should do the job. 

> prevents Webex and any other application from making its taskbar icon flash

This part means that you *may* try to use this piece of software for software other than WebEx, but it only targets one program at a time.

**Comment by lacaulac** [comment]
To finish answering your question (since I apparently can't read a whole message in one go), the only thing you've got to do in order to revert the changes is to restart WebEx. Unfortunately, you've got to start the injector program everytime you start WebEx / wish to disable the flashing. If you don't run the injector after a fresh instance of WebEx has been launched, it'll still flash like crazy.

**Comment by swingcake** [comment]
> (since I apparently can't read a whole message in one go)

Gotcha haha, no worries it happens

Would you be able to provide the executable (uploaded to google drive maybe?)

**Comment by lacaulac** [comment]
Sure, I'll make a fresh build tomorrow and check VirusTotal in case AV-detection shenanigans happen again (see #1).
If everything's good to go I'll then send it your way :)

**Comment by swingcake** [comment]
Yes, I'm aware of that. I trust you (either that or am endlessly annoyed by this "feature")

![chrome_2021-06-15_01-07-38](https://user-images.githubusercontent.com/32037820/121949566-3a20df80-cd76-11eb-9298-c685b1ea34b1.png)

**Comment by lacaulac** [comment]
I've built the binaries, but after looking at the virustotal scan results on the newly built Injector (https://www.virustotal.com/gui/file/08ae54ce5479d32f960eef1b4d50c0f6067b829d9870918d593b83c13d36f69b/detection), I've found some really concerning elements relating to the sigma rules. I'm afraid I don't think that distributing the binaries in the current situation is safe at all. I'll get back to you when I've fixed that issue.

**Comment by lacaulac** [comment]
Hey, sorry for the delay, I didn't get much time to look into this issue.
I found a build that I suspect is quite old, but was apparently working and installed in my WebEx folder.
For some reason, this one [doesn't get flagged by AVs](https://www.virustotal.com/gui/file/0d75fc7e171881f781992e177db9e66b8a1be0824b2238448068d8e0c7581ae4/detection) as much as the newer builds, so I tagged it as a release.
Unfortunately, I've not been able to find a non-detected build of the DLL Injector, and will thus not be providing one at the moment. In order to use this project, I'm afraid that you will have to resort to standard DLL Injectors. I'd recommend [Process Hacker](https://processhacker.sourceforge.io/)'s (*Right-click on atmgr.exe's process> Miscellaneous > Inject DLL > Select WebexAntiFlash.dll*).
The release is available [here](https://github.com/lacaulac/webex-anti-flash/releases/tag/1.0).
